### ISSUE TITLE
`inert` attribute remedy?

### ISSUE THREAD

**Issue by Malvoz** [jensimmons/cssremedy#87]
See https://github.com/WICG/inert/issues/180 for background.

I.e. something along the lines of:

```css
[inert] {
  cursor: default !important;
  pointer-events: none !important;
}

[inert], [inert] * {
-webkit-user-modify: read-only !important;
   -moz-user-modify: read-only !important;
        user-modify: read-only !important;
-webkit-user-select: none !important;
   -moz-user-select: none !important;
    -ms-user-select: none !important;
        user-select: none !important;
}
```
